//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TorboFile.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CustomSearchStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CustomSearchStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TorboFile.Properties.CustomSearchStrings", typeof(CustomSearchStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matched Files and Directories will be deleted. This action cannot be undone..
        /// </summary>
        public static string ACTION_DELETE_MSG {
            get {
                return ResourceManager.GetString("ACTION_DELETE_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Recycle Bin will be emptied. This action cannot be undone..
        /// </summary>
        public static string action_empty_recycle_msg {
            get {
                return ResourceManager.GetString("action_empty_recycle_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Directories.
        /// </summary>
        public static string action_move_create_opt {
            get {
                return ResourceManager.GetString("action_move_create_opt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create any missing destination folders..
        /// </summary>
        public static string action_move_create_tip {
            get {
                return ResourceManager.GetString("action_move_create_tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moves Files and Directories to the given location..
        /// </summary>
        public static string action_move_msg {
            get {
                return ResourceManager.GetString("action_move_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The destination entered is a Relative File Path. Files will be moved relative to their locations..
        /// </summary>
        public static string action_move_rel_msg {
            get {
                return ResourceManager.GetString("action_move_rel_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matched Files and Directories will be moved to the Recycle Bin..
        /// </summary>
        public static string action_recycle_msg {
            get {
                return ResourceManager.GetString("action_recycle_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace String:.
        /// </summary>
        public static string action_regex_dst {
            get {
                return ResourceManager.GetString("action_regex_dst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename all matches of the regular expression in the file or directory name by the given replacement string..
        /// </summary>
        public static string action_regex_msg {
            get {
                return ResourceManager.GetString("action_regex_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Expression:.
        /// </summary>
        public static string action_regex_src {
            get {
                return ResourceManager.GetString("action_regex_src", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace:.
        /// </summary>
        public static string action_rename_dst {
            get {
                return ResourceManager.GetString("action_rename_dst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename all occurances of the given string in a file or directory name..
        /// </summary>
        public static string action_rename_msg {
            get {
                return ResourceManager.GetString("action_rename_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search:.
        /// </summary>
        public static string action_rename_src {
            get {
                return ResourceManager.GetString("action_rename_src", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclude Matches.
        /// </summary>
        public static string exclude_option {
            get {
                return ResourceManager.GetString("exclude_option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If checked, only items that do NOT match this requirement will be included in results..
        /// </summary>
        public static string exclude_tip {
            get {
                return ResourceManager.GetString("exclude_tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only directories will be included in the search results..
        /// </summary>
        public static string IS_FILE_EXCLUDE {
            get {
                return ResourceManager.GetString("IS_FILE_EXCLUDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directories will be excluded from the search results..
        /// </summary>
        public static string IS_FILE_INCLUDE {
            get {
                return ResourceManager.GetString("IS_FILE_INCLUDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Search....
        /// </summary>
        public static string LOAD_SEARCH_MSG {
            get {
                return ResourceManager.GetString("LOAD_SEARCH_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directories with the given number of sub-files will be excluded from search results..
        /// </summary>
        public static string MATCH_COUNT_EXCLUDE {
            get {
                return ResourceManager.GetString("MATCH_COUNT_EXCLUDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directories with the given number of sub-files will be included in search results..
        /// </summary>
        public static string MATCH_COUNT_INCLUDE {
            get {
                return ResourceManager.GetString("MATCH_COUNT_INCLUDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Files:.
        /// </summary>
        public static string match_count_max_prompt {
            get {
                return ResourceManager.GetString("match_count_max_prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directories containing more files will not be matched..
        /// </summary>
        public static string match_count_max_tip {
            get {
                return ResourceManager.GetString("match_count_max_tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min Files:.
        /// </summary>
        public static string match_count_min_prompt {
            get {
                return ResourceManager.GetString("match_count_min_prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directories containing fewer files will not be matched..
        /// </summary>
        public static string match_count_min_tip {
            get {
                return ResourceManager.GetString("match_count_min_tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match directories which contain a given number of sub-files. Files are also included in the search, unless a Directory-Only condition is added..
        /// </summary>
        public static string match_count_prompt {
            get {
                return ResourceManager.GetString("match_count_prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subdirectories count against total..
        /// </summary>
        public static string match_count_subdir_opt {
            get {
                return ResourceManager.GetString("match_count_subdir_opt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty directories will be excluded from the search..
        /// </summary>
        public static string match_empty_dir_exclude {
            get {
                return ResourceManager.GetString("match_empty_dir_exclude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty directories will be included in the search..
        /// </summary>
        public static string match_empty_dir_include {
            get {
                return ResourceManager.GetString("match_empty_dir_include", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty Directories.
        /// </summary>
        public static string match_empty_dir_title {
            get {
                return ResourceManager.GetString("match_empty_dir_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files with these extensions will not be included in the search..
        /// </summary>
        public static string MATCH_EXT_EXCLUDE {
            get {
                return ResourceManager.GetString("MATCH_EXT_EXCLUDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files with these extensions will be included in the search. Directories are also allowed..
        /// </summary>
        public static string MATCH_EXT_INCLUDE {
            get {
                return ResourceManager.GetString("MATCH_EXT_INCLUDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allowed File Extensions:.
        /// </summary>
        public static string match_ext_prompt {
            get {
                return ResourceManager.GetString("match_ext_prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Separate extensions with &apos;;&apos; or &apos;,&apos;.
        /// </summary>
        public static string match_ext_tip {
            get {
                return ResourceManager.GetString("match_ext_tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files and directories with names containing the given string will be excluded from the search..
        /// </summary>
        public static string MATCH_NAME_EXCLUDE {
            get {
                return ResourceManager.GetString("MATCH_NAME_EXCLUDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Full Path.
        /// </summary>
        public static string match_name_full_opt {
            get {
                return ResourceManager.GetString("match_name_full_opt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If checked, the entire file path is searched for the match string..
        /// </summary>
        public static string match_name_full_tip {
            get {
                return ResourceManager.GetString("match_name_full_tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files and directories with names containing the given string will be included in the search..
        /// </summary>
        public static string MATCH_NAME_INCLUDE {
            get {
                return ResourceManager.GetString("MATCH_NAME_INCLUDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File/Dictory Name contains:.
        /// </summary>
        public static string match_name_prompt {
            get {
                return ResourceManager.GetString("match_name_prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files and directories matching the regular expression will be excluded from search results..
        /// </summary>
        public static string MATCH_REG_EXCLUDE {
            get {
                return ResourceManager.GetString("MATCH_REG_EXCLUDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only files and directories matching the regular expression will be included in the search..
        /// </summary>
        public static string MATCH_REG_INCLUDE {
            get {
                return ResourceManager.GetString("MATCH_REG_INCLUDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Mode:.
        /// </summary>
        public static string match_reg_mode_opt {
            get {
                return ResourceManager.GetString("match_reg_mode_opt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Expression:.
        /// </summary>
        public static string match_reg_prompt {
            get {
                return ResourceManager.GetString("match_reg_prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excludes any files in the given size range. Directories are also matched unless a File-Only condition is added..
        /// </summary>
        public static string MATCH_SIZE_EXCLUDE {
            get {
                return ResourceManager.GetString("MATCH_SIZE_EXCLUDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limits the search to files in the given size range. Directories are also matched unless a File-Only condition is added..
        /// </summary>
        public static string MATCH_SIZE_INCLUDE {
            get {
                return ResourceManager.GetString("MATCH_SIZE_INCLUDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Size (bytes):.
        /// </summary>
        public static string match_size_max_prompt {
            get {
                return ResourceManager.GetString("match_size_max_prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min Size (bytes):.
        /// </summary>
        public static string match_size_min_prompt {
            get {
                return ResourceManager.GetString("match_size_min_prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Search....
        /// </summary>
        public static string SAVE_SEARCH_MSG {
            get {
                return ResourceManager.GetString("SAVE_SEARCH_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SEARCH_DIR_PROMPT {
            get {
                return ResourceManager.GetString("SEARCH_DIR_PROMPT", resourceCulture);
            }
        }
    }
}
