//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TorboFile.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MainStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MainStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TorboFile.Properties.MainStrings", typeof(MainStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio.
        /// </summary>
        public static string AUDIO_TYPE_NAME {
            get {
                return ResourceManager.GetString("AUDIO_TYPE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Categories.
        /// </summary>
        public static string BTN_EDIT_CATEGORIES_TIP {
            get {
                return ResourceManager.GetString("BTN_EDIT_CATEGORIES_TIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Category.
        /// </summary>
        public static string BTN_NEW_CATEGORY_TIP {
            get {
                return ResourceManager.GetString("BTN_NEW_CATEGORY_TIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories:.
        /// </summary>
        public static string CATEGORIES_HEADER {
            get {
                return ResourceManager.GetString("CATEGORIES_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string CATEGORY_HEADER {
            get {
                return ResourceManager.GetString("CATEGORY_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Name.
        /// </summary>
        public static string CATEGORY_NAME {
            get {
                return ResourceManager.GetString("CATEGORY_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Path.
        /// </summary>
        public static string CATEGORY_PATH {
            get {
                return ResourceManager.GetString("CATEGORY_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sets:.
        /// </summary>
        public static string CATEGORY_SETS_HEADER {
            get {
                return ResourceManager.GetString("CATEGORY_SETS_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Begin Clean.
        /// </summary>
        public static string CLEAN_DIRS_BEGIN_PROMPT {
            get {
                return ResourceManager.GetString("CLEAN_DIRS_BEGIN_PROMPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Empty Files.
        /// </summary>
        public static string CLEAN_DIRS_EMPTY_OPT {
            get {
                return ResourceManager.GetString("CLEAN_DIRS_EMPTY_OPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove any files of Size 0. (File contains no data).
        /// </summary>
        public static string CLEAN_DIRS_EMPTY_TIP {
            get {
                return ResourceManager.GetString("CLEAN_DIRS_EMPTY_TIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Size:.
        /// </summary>
        public static string CLEAN_DIRS_MAX_MSG {
            get {
                return ResourceManager.GetString("CLEAN_DIRS_MAX_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min Size:.
        /// </summary>
        public static string CLEAN_DIRS_MIN_MSG {
            get {
                return ResourceManager.GetString("CLEAN_DIRS_MIN_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a folder to delete all empty sub-folders. If recursive is checked, folders containing only other folders, or unwanted files, are also removed..
        /// </summary>
        public static string CLEAN_DIRS_MSG {
            get {
                return ResourceManager.GetString("CLEAN_DIRS_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recursive Clean.
        /// </summary>
        public static string CLEAN_DIRS_RECURSIVE_OPT {
            get {
                return ResourceManager.GetString("CLEAN_DIRS_RECURSIVE_OPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include all subfolders of the chosen folder in the search..
        /// </summary>
        public static string CLEAN_DIRS_RECURSIVE_TIP {
            get {
                return ResourceManager.GetString("CLEAN_DIRS_RECURSIVE_TIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete files of size:.
        /// </summary>
        public static string CLEAN_DIRS_SIZE_OPT {
            get {
                return ResourceManager.GetString("CLEAN_DIRS_SIZE_OPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check to delete any files found within the specified size range..
        /// </summary>
        public static string CLEAN_DIRS_SIZE_TIP {
            get {
                return ResourceManager.GetString("CLEAN_DIRS_SIZE_TIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It&apos;s a Confirm button..
        /// </summary>
        public static string CONFIRM_BTN_TIP {
            get {
                return ResourceManager.GetString("CONFIRM_BTN_TIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted Files:.
        /// </summary>
        public static string COPIES_DELETE_HEADER {
            get {
                return ResourceManager.GetString("COPIES_DELETE_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Permanently.
        /// </summary>
        public static string COPIES_DELETE_OPT {
            get {
                return ResourceManager.GetString("COPIES_DELETE_OPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclude these file types: ( separate file extensions with &apos;;&apos; or &apos;,&apos; ).
        /// </summary>
        public static string COPIES_EXCLUDE_PROMPT {
            get {
                return ResourceManager.GetString("COPIES_EXCLUDE_PROMPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search File Extensions:.
        /// </summary>
        public static string COPIES_EXT_HEADER {
            get {
                return ResourceManager.GetString("COPIES_EXT_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of file extensions separated by &apos;;&apos; or &apos;,&apos;.
        /// </summary>
        public static string COPIES_EXT_TIP {
            get {
                return ResourceManager.GetString("COPIES_EXT_TIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only Include these file types: ( separate file extensions with &apos;;&apos; or &apos;,&apos; ).
        /// </summary>
        public static string COPIES_INCLUDE_PROMPT {
            get {
                return ResourceManager.GetString("COPIES_INCLUDE_PROMPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move To Recycle Bin.
        /// </summary>
        public static string COPIES_MOVE_RECYCLE_OPT {
            get {
                return ResourceManager.GetString("COPIES_MOVE_RECYCLE_OPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Options:.
        /// </summary>
        public static string COPIES_OPTIONS_MSG {
            get {
                return ResourceManager.GetString("COPIES_OPTIONS_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recursive Search:.
        /// </summary>
        public static string COPIES_RECURSIVE_HEADER {
            get {
                return ResourceManager.GetString("COPIES_RECURSIVE_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Subfolders.
        /// </summary>
        public static string COPIES_RECURSIVE_OPT {
            get {
                return ResourceManager.GetString("COPIES_RECURSIVE_OPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember Search File Extensions.
        /// </summary>
        public static string COPIES_SAVE_EXT_OPT {
            get {
                return ResourceManager.GetString("COPIES_SAVE_EXT_OPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Size (bytes):.
        /// </summary>
        public static string COPIES_SIZE_MAX {
            get {
                return ResourceManager.GetString("COPIES_SIZE_MAX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min Size (bytes):.
        /// </summary>
        public static string COPIES_SIZE_MIN {
            get {
                return ResourceManager.GetString("COPIES_SIZE_MIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Size Range.
        /// </summary>
        public static string COPIES_SIZE_OPT {
            get {
                return ResourceManager.GetString("COPIES_SIZE_OPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete File.
        /// </summary>
        public static string DELETE_FILE_TIP {
            get {
                return ResourceManager.GetString("DELETE_FILE_TIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string FILE_NAME_HEADER {
            get {
                return ResourceManager.GetString("FILE_NAME_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File:.
        /// </summary>
        public static string FILE_NAME_MSG {
            get {
                return ResourceManager.GetString("FILE_NAME_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path.
        /// </summary>
        public static string FILE_PATH_HEADER {
            get {
                return ResourceManager.GetString("FILE_PATH_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        public static string FILE_SIZE_HEADER {
            get {
                return ResourceManager.GetString("FILE_SIZE_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string IMAGE_TYPE_NAME {
            get {
                return ResourceManager.GetString("IMAGE_TYPE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key Binding.
        /// </summary>
        public static string KEY_BINDING_HEADER {
            get {
                return ResourceManager.GetString("KEY_BINDING_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next File.
        /// </summary>
        public static string NEXT_FILE_TIP {
            get {
                return ResourceManager.GetString("NEXT_FILE_TIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open External....
        /// </summary>
        public static string OPEN_EXTERNAL_PROMPT {
            get {
                return ResourceManager.GetString("OPEN_EXTERNAL_PROMPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Externally.
        /// </summary>
        public static string OPEN_EXTERNAL_TIP {
            get {
                return ResourceManager.GetString("OPEN_EXTERNAL_TIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mime Type:.
        /// </summary>
        public static string PREVIEW_MIME_MSG {
            get {
                return ResourceManager.GetString("PREVIEW_MIME_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try View As:.
        /// </summary>
        public static string PREVIEW_TRY_VIEW_PROMPT {
            get {
                return ResourceManager.GetString("PREVIEW_TRY_VIEW_PROMPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown File Type.
        /// </summary>
        public static string PREVIEW_UNKNOWN_MSG {
            get {
                return ResourceManager.GetString("PREVIEW_UNKNOWN_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous File.
        /// </summary>
        public static string PREVIOUS_FILE_TIP {
            get {
                return ResourceManager.GetString("PREVIOUS_FILE_TIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Selected Size:.
        /// </summary>
        public static string SELECTED_SIZE_MSG {
            get {
                return ResourceManager.GetString("SELECTED_SIZE_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Name.
        /// </summary>
        public static string SET_NAME_HEADER {
            get {
                return ResourceManager.GetString("SET_NAME_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Name:.
        /// </summary>
        public static string SET_NAME_PROMPT {
            get {
                return ResourceManager.GetString("SET_NAME_PROMPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show In Explorer.
        /// </summary>
        public static string SHOW_IN_EXPLORER_TIP {
            get {
                return ResourceManager.GetString("SHOW_IN_EXPLORER_TIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        public static string SORT_BROWSE_HEADER {
            get {
                return ResourceManager.GetString("SORT_BROWSE_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go To Folder.
        /// </summary>
        public static string SORT_BROWSE_TIP {
            get {
                return ResourceManager.GetString("SORT_BROWSE_TIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Directory.
        /// </summary>
        public static string SORT_CHANGE_DIR_TIP {
            get {
                return ResourceManager.GetString("SORT_CHANGE_DIR_TIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick Key.
        /// </summary>
        public static string SORT_KEYBIND_HEADER {
            get {
                return ResourceManager.GetString("SORT_KEYBIND_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press to move Current File to Category.
        /// </summary>
        public static string SORT_KEYBIND_TIP {
            get {
                return ResourceManager.GetString("SORT_KEYBIND_TIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string SORT_MOVETO_HEADER {
            get {
                return ResourceManager.GetString("SORT_MOVETO_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move file to Category.
        /// </summary>
        public static string SORT_MOVETO_TIP {
            get {
                return ResourceManager.GetString("SORT_MOVETO_TIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        public static string TEXT_TYPE_NAME {
            get {
                return ResourceManager.GetString("TEXT_TYPE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video.
        /// </summary>
        public static string VIDEO_TYPE_NAME {
            get {
                return ResourceManager.GetString("VIDEO_TYPE_NAME", resourceCulture);
            }
        }
    }
}
