//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TorboFile.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.5.0.0")]
    internal sealed partial class PreviewSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static PreviewSettings defaultInstance = ((PreviewSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new PreviewSettings())));
        
        public static PreviewSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Default")]
        public global::TorboFile.Properties.ViewMode imageViewMode {
            get {
                return ((global::TorboFile.Properties.ViewMode)(this["imageViewMode"]));
            }
            set {
                this["imageViewMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Default")]
        public global::TorboFile.Properties.ViewMode mediaViewMode {
            get {
                return ((global::TorboFile.Properties.ViewMode)(this["mediaViewMode"]));
            }
            set {
                this["mediaViewMode"] = value;
            }
        }
    }
}
